name: 'Detect unmergeable Pull Request'
description: 'Detect unmergeable pull requests. This actions labels such PRs and mention suspicious changes'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'bell'  
  color: 'purple'