version: 2.1

###########################################
# Constants
###########################################
workspace_root: &workspace_root
    /tmp/workspace

###########################################
# Executors Definitions
###########################################
executors:
    build_executor:
        working_directory: *workspace_root
        docker:
            - image: golang:1.13-buster


###########################################
# Commands Definitions
###########################################
commands:


###########################################
# Job Definitions
###########################################
jobs:
   build_for_every_change:
        executor: build_executor
        steps:
            - checkout
            - run: make build -j


###########################################
# Workflow Definitions
###########################################
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_for_every_change
